name: Essence
version: '${project.version}'
main: com.idk.essence.Essence
api-version: 1.21
softdepend: [ PlaceholderAPI ]
authors: [ IDontKnow ]
description: The purest power of essence.
commands:
  essence:
    usage: /<command>
    description: A main command in the plugin
    aliases:
      - es
